development:
  bin_path: '/usr/local/bin'
  enable_star: 1
  min_infix_len: 3
  morphology: stem_en
  port: 3312

production:
  bin_path: '/usr/local/bin'
  enable_star: 1
  min_infix_len: 3
  morphology: stem_en
  port: 3312

staging:
  bin_path: '/usr/local/bin'
  enable_star: 1
  min_infix_len: 3
  morphology: stem_en
  port: 3313

